<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<title>Content-Centric Networking in Java: org.ccnx.ccn.test.ThreadAssertionRunner Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<!-- Generated by Doxygen 1.6.3 -->
<div class="navigation" id="top">
  <div class="tabs">
    <ul>
      <li><a href="main.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.html"><span>Related&nbsp;Pages</span></a></li>
      <li><a href="namespaces.html"><span>Packages</span></a></li>
      <li class="current"><a href="annotated.html"><span>Classes</span></a></li>
    </ul>
  </div>
  <div class="tabs">
    <ul>
      <li><a href="annotated.html"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.html"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.html"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
  <div class="navpath"><b>org</b>.<b>ccnx</b>.<b>ccn</b>.<a class="el" href="namespaceorg_1_1ccnx_1_1ccn_1_1test.html">test</a>.<a class="el" href="classorg_1_1ccnx_1_1ccn_1_1test_1_1_thread_assertion_runner.html">ThreadAssertionRunner</a>
  </div>
</div>
<div class="contents">
<h1>org.ccnx.ccn.test.ThreadAssertionRunner Class Reference</h1><!-- doxytag: class="org::ccnx::ccn::test::ThreadAssertionRunner" -->
<p>Junit cannot catch exceptions from spawned threads.  
<a href="#_details">More...</a></p>

<p><a href="classorg_1_1ccnx_1_1ccn_1_1test_1_1_thread_assertion_runner-members.html">List of all members.</a></p>
<table border="0" cellpadding="0" cellspacing="0">
<tr><td colspan="2"><h2>Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0a744f71df88409a81b29b82a06d6fca"></a><!-- doxytag: member="org::ccnx::ccn::test::ThreadAssertionRunner::ThreadAssertionRunner" ref="a0a744f71df88409a81b29b82a06d6fca" args="(final Runnable runner)" -->
&nbsp;</td><td class="memItemRight" valign="bottom"><b>ThreadAssertionRunner</b> (final <a class="el" href="class_runnable.html">Runnable</a> runner)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a06ae0483b1ba1a739681f3e0e841350c"></a><!-- doxytag: member="org::ccnx::ccn::test::ThreadAssertionRunner::start" ref="a06ae0483b1ba1a739681f3e0e841350c" args="()" -->
void&nbsp;</td><td class="memItemRight" valign="bottom"><b>start</b> ()</td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="adce4c6710b958cd5e5cdfc84cbff9895"></a><!-- doxytag: member="org::ccnx::ccn::test::ThreadAssertionRunner::join" ref="adce4c6710b958cd5e5cdfc84cbff9895" args="()" -->
void&nbsp;</td><td class="memItemRight" valign="bottom"><b>join</b> ()  throws InterruptedException, Error, Exception </td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa3000217030f4d9f33efeeef70cd23d1"></a><!-- doxytag: member="org::ccnx::ccn::test::ThreadAssertionRunner::join" ref="aa3000217030f4d9f33efeeef70cd23d1" args="(long millis)" -->
void&nbsp;</td><td class="memItemRight" valign="bottom"><b>join</b> (long millis)  throws InterruptedException, Error, Exception </td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aaf0c4315f866dbc822660a70cad5c1fb"></a><!-- doxytag: member="org::ccnx::ccn::test::ThreadAssertionRunner::isAlive" ref="aaf0c4315f866dbc822660a70cad5c1fb" args="()" -->
boolean&nbsp;</td><td class="memItemRight" valign="bottom"><b>isAlive</b> ()</td></tr>
</table>
<hr/><a name="_details"></a><h2>Detailed Description</h2>
<p>Junit cannot catch exceptions from spawned threads. </p>
<p>This wrapper class will catch assertion failures in a <a class="el" href="class_runnable.html">Runnable</a> and report them to the caller.</p>
<p>Junit Assert.X method throw an AssertionError, which is a Throwable -&gt; Error -&gt; AssertionError. So, we capture both an Error and an <a class="el" href="class_exception.html">Exception</a>. Don't use Throwable, as those get messy to handle in the caller.</p>
<p>How to use: 1) Create a <a class="el" href="class_runnable.html">Runnable</a> class (could even be anonymous inner class), and wrap it in a <a class="el" href="classorg_1_1ccnx_1_1ccn_1_1test_1_1_thread_assertion_runner.html" title="Junit cannot catch exceptions from spawned threads.">ThreadAssertionRunner</a>:</p>
<p><a class="el" href="classorg_1_1ccnx_1_1ccn_1_1test_1_1_thread_assertion_runner.html" title="Junit cannot catch exceptions from spawned threads.">ThreadAssertionRunner</a> tar = new <a class="el" href="classorg_1_1ccnx_1_1ccn_1_1test_1_1_thread_assertion_runner.html" title="Junit cannot catch exceptions from spawned threads.">ThreadAssertionRunner</a>(new MyRunner(some_parameter));</p>
<p>2) Start the Runner like a thread:</p>
<p>tar.start();</p>
<p>3) Do normal processing, then stop your runnable. You must join the Runner to wait for exit. THIS STEP IS REQUIRED (it's the join that reports any exceptions or errors from the run() method of your runnable):</p>
<p>tar.join(); </p>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>src/org/ccnx/ccn/test/ThreadAssertionRunner.java</li>
</ul>
</div>
<hr class="footer"/><address style="text-align: right;"><small>Generated on Mon Feb 4 11:59:05 2013 for Content-Centric Networking in Java by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.6.3 </small></address>
</body>
</html>
